components:
    schemas:
        AppWorkflow:
            properties:
                appId:
                    format: int64
                    type: integer
                appWorkflowStates:
                    items:
                        $ref: "#/components/schemas/AppWorkflowState"
                    type: array
                appWorkflowTasks:
                    items:
                        $ref: "#/components/schemas/AppWorkflowTask"
                    type: array
            type: object
        AppWorkflowState:
            properties:
                appWorkflowTransitions:
                    items:
                        $ref: "#/components/schemas/AppWorkflowTransition"
                    type: array
                initial:
                    type: boolean
                name:
                    type: string
            type: object
        AppWorkflowTask:
            properties:
                appWorkflowTransitions:
                    items:
                        $ref: "#/components/schemas/AppWorkflowTransition"
                    type: array
                dataLayoutIds:
                    items:
                        format: int64
                        type: integer
                    type: array
                name:
                    type: string
            type: object
        AppWorkflowTransition:
            properties:
                name:
                    type: string
                primary:
                    type: boolean
                transitionTo:
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.app.builder.workflow.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "App Builder Workflow"
    version: v1.0
openapi: 3.0.1
paths:
    "/apps/{appId}/app-workflows":
        get:
            operationId: getAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                    description:
                        ""
            tags: ["AppWorkflow"]
        post:
            operationId: postAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                    description:
                        ""
            tags: ["AppWorkflow"]
        put:
            operationId: putAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                    description:
                        ""
            tags: ["AppWorkflow"]